<?php
/**
 * @category   Udeytech
 * @package    Udeytech_Hardik
 * @author     hardik044udeytech@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Udeytech\Hardik\Block;

use Magento\Framework\View\Element\Template\Context;
use Udeytech\Hardik\Model\HardikFactory;
/**
 * Hardik List block
 */
class HardikListData extends \Magento\Framework\View\Element\Template
{
    /**
     * @var Hardik
     */
    protected $_hardik;
    public function __construct(
        Context $context,
        HardikFactory $hardik
    ) {
        $this->_hardik = $hardik;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('Udeytech Hardik Module List Page'));
        
        if ($this->getHardikCollection()) {
            $pager = $this->getLayout()->createBlock(
                'Magento\Theme\Block\Html\Pager',
                'udeytech.hardik.pager'
            )->setAvailableLimit(array(5=>5,10=>10,15=>15))->setShowPerPage(true)->setCollection(
                $this->getHardikCollection()
            );
            $this->setChild('pager', $pager);
            $this->getHardikCollection()->load();
        }
        return parent::_prepareLayout();
    }

    public function getHardikCollection()
    {
        $page = ($this->getRequest()->getParam('p'))? $this->getRequest()->getParam('p') : 1;
        $pageSize = ($this->getRequest()->getParam('limit'))? $this->getRequest()->getParam('limit') : 5;

        $hardik = $this->_hardik->create();
        $collection = $hardik->getCollection();
        $collection->addFieldToFilter('status','1');
        //$hardik->setOrder('hardik_id','ASC');
        $collection->setPageSize($pageSize);
        $collection->setCurPage($page);

        return $collection;
    }

    public function getPagerHtml()
    {
        return $this->getChildHtml('pager');
    }
}