<?php
/**
 * @category   Udeytech
 * @package    Udeytech_Hardik
 * @author     hardik044udeytech@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Udeytech\Hardik\Block;

use Magento\Framework\View\Element\Template\Context;
use Udeytech\Hardik\Model\HardikFactory;
use Magento\Cms\Model\Template\FilterProvider;
/**
 * Hardik View block
 */
class HardikView extends \Magento\Framework\View\Element\Template
{
    /**
     * @var Hardik
     */
    protected $_hardik;
    public function __construct(
        Context $context,
        HardikFactory $hardik,
        FilterProvider $filterProvider
    ) {
        $this->_hardik = $hardik;
        $this->_filterProvider = $filterProvider;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('Udeytech Hardik Module View Page'));
        
        return parent::_prepareLayout();
    }

    public function getSingleData()
    {
        $id = $this->getRequest()->getParam('id');
        $hardik = $this->_hardik->create();
        $singleData = $hardik->load($id);
        if($singleData->getHardikId() || $singleData['hardik_id'] && $singleData->getStatus() == 1){
            return $singleData;
        }else{
            return false;
        }
    }
}